"""Shared constants for the rules package."""

REEL_REVIEW_MIN_PACK_QTY = 250
LARGE_PACK_REVIEW_MIN_PACK_QTY = 25
CONFIRMED_STOCKING_MAX_SESSIONS_WITHOUT_EVIDENCE = 3
SUGGESTION_VS_HISTORY_GAP_THRESHOLD = 0.5

PACK_MAX_RATIO_FOR_LARGE_PACK = 3
MAX_CREDIBILITY_PACK_RATIO = 5.0  # if pack > max * this, max is probably auto-noise
HEURISTIC_WEEKLY_PACK_RATIO = 0.75
HEURISTIC_WEEKLY_MAX_RATIO = 1.5
HEURISTIC_ANNUAL_PACK_RATIO = 18.0
HEURISTIC_ANNUAL_MAX_RATIO = 24.0
HEURISTIC_MIN_SALES_SPAN_DAYS = 180
HEURISTIC_SHORT_SPAN_DAYS = 14
HEURISTIC_COVER_WEEKLY_PACK_RATIO = 0.85
HEURISTIC_COVER_WEEKLY_MAX_RATIO = 1.75
HEURISTIC_COVER_ANNUAL_PACK_RATIO = 26.0
HEURISTIC_COVER_ANNUAL_MAX_RATIO = 40.0
HEURISTIC_MAX_DAYS_SINCE_SALE = 120
HEURISTIC_HIGH_CONFIDENCE_THRESHOLD = 0.75
DEFAULT_LEAD_TIME_DAYS = 14
DEAD_STOCK_MIN_DAYS_SINCE_SALE = 365

REEL_BLOCKLIST = (
    "BELT", "BOLT", "BOLTS", "NUT", "NUTS", "WASHER", "WASHERS",
    "SCREW", "SCREWS", "CLAMP", "CLAMPS", "FITTING", "FITTINGS",
    "FERRULE", "FERRULES", "NIPPLE", "NIPPLES", "SLEEVE", "SLEEVES",
    "SPROCKET", "SPROCKETS", "BEARING", "BEARINGS", "ASSY", "ASSEMBLY",
    "BRUSH", "CUTTER", "TIE", "TIES",
)
REEL_STRONG_PHRASES = ("AIRCRAFT CABLE", "AIRBRAKE TUBE")
REEL_BASE_TERMS = ("HOSE", "CABLE", "TUBE", "TUBING", "CORD", "ROPE")
REEL_LENGTH_TERMS = (" FT", "FT ", "100FT", "X100F", "X 100F", "ROLL", "COIL", "SPOOL")
HARDWARE_PACK_TERMS = (
    "BOLT", "BOLTS", "NUT", "NUTS", "WASHER", "WASHERS",
    "SCREW", "SCREWS", "CLAMP", "CLAMPS", "FITTING", "FITTINGS",
    "FASTENER", "FASTENERS",
)
